name: intake-thredds-dev
channels:
  - conda-forge
dependencies:
  - python=*=*cp*
  - aiohttp
  - codecov
  - intake
  - intake-xarray
  - netcdf4
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - siphon
  - tqdm
  - xarray
  - pydap
  - aiohttp
  - h5netcdf
