name: intake-thredds-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - h5netcdf
  - netcdf4
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - tqdm
  - xarray
  - aiohttp
  - pip:
      - git+https://github.com/intake/intake.git
      - git+https://github.com/intake/intake-xarray.git
      - git+https://github.com/Unidata/siphon.git
