name: intake-thredds-dev
channels:
  - conda-forge
dependencies:
  - codecov
  - intake
  - netcdf4
  - pip
  - pytest
  - pytest-cov
  - pytest-icdiff
  - pytest-xdist
  - siphon
  - tqdm
  - xarray
  - aiohttp
  - pip:
      - git+https://github.com/intake/intake_xarray.git
