name: intake-thredds-dev
channels:
  - conda-forge
dependencies:
  - dask
  - jupyterlab>=3
  - myst-nb >=0.11.1
  - pip
  - pydata-sphinx-theme>=0.4.3
  - python=3.8
  - tqdm
  - intake-xarray
  - fsspec
  - siphon
  - pip: -r ../requirements.txt
